package com.chillpavz.seamlessores.config;

import java.util.ArrayList;
import java.util.List;

import com.chillpavz.seamlessores.Constants;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractSliderButton;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.Tooltip;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.CommonComponents;
import net.minecraft.network.chat.Component;
import net.minecraftforge.common.ForgeConfigSpec;

/**
 * Client-only config screen for the Forge build, reached from the mods list.
 *
 * <p>Cloth Config has no Forge build past 1.21.3, and neither Configured nor Forge Config Screens
 * has a 1.21.11 Forge build, so where Fabric and NeoForge get a generated Cloth screen, Forge needs
 * this hand-written one. It reuses the Cloth lang keys verbatim - {@code text.autoconfig.<id>.*} -
 * so every label, tooltip and category title reads identically on all three loaders and there is
 * only one set of strings to maintain (they are generated by {@code tools/generate_assets.py}).
 *
 * <p>Laid out as four category tabs rather than one long list: fifteen options do not fit on a
 * screen, and the tabs mirror how Cloth presents the same four categories. Each page is short
 * enough to need no scrolling, so there is no list widget here at all.
 *
 * <p>Values are held in the widgets and written back to the spec once, on close - the same
 * behaviour as Cloth's own screen, where nothing is saved until you leave.
 */
public class SeamlessOresConfigScreen extends Screen {

    private static final int ROW_HEIGHT = 24;
    private static final int ROW_WIDTH = 310;
    private static final int WIDGET_HEIGHT = 20;
    private static final int RESET_WIDTH = 50;
    private static final int GAP = 4;
    private static final int OPTION_WIDTH = ROW_WIDTH - RESET_WIDTH - GAP;
    private static final int TAB_HEIGHT = 20;
    private static final int HEADER_BOTTOM = 56;

    /** The four categories, in the same order as the Cloth screen. */
    private static final String[] CATEGORIES = {"overworld", "nether", "create", "mythic_upgrades"};

    private final Screen parent;
    /** Every option on every page, so Done and Reset all reach the pages you never opened. */
    private final List<Option> options = new ArrayList<>();
    private int category = 0;

    public SeamlessOresConfigScreen(Screen parent) {
        super(Component.translatable("text.autoconfig." + Constants.MOD_ID + ".title"));
        this.parent = parent;
        buildOptions();
    }

    /**
     * Builds the option models once, in the constructor rather than in {@link #init()}.
     *
     * <p>That is the whole reason a switch between tabs does not lose your edits: the widgets are
     * thrown away and rebuilt on every {@code init()}, but the pending value lives on the Option.
     */
    private void buildOptions() {
        options.add(new BoolOption("overworld", "granite", SeamlessOresConfigData.GRANITE, true));
        options.add(new BoolOption("overworld", "diorite", SeamlessOresConfigData.DIORITE, true));
        options.add(new BoolOption("overworld", "andesite", SeamlessOresConfigData.ANDESITE, true));
        options.add(new BoolOption("overworld", "tuff", SeamlessOresConfigData.TUFF, true));
        options.add(new BoolOption("overworld", "oreVeins", SeamlessOresConfigData.ORE_VEINS, true));

        options.add(new BoolOption("nether", "basalt", SeamlessOresConfigData.BASALT, true));
        options.add(new BoolOption("nether", "blackstone", SeamlessOresConfigData.BLACKSTONE, true));
        options.add(new BoolOption("nether", "bastionSafeNether",
                SeamlessOresConfigData.BASTION_SAFE_NETHER, true));
        options.add(new IntOption("nether", "netherOreRarity", SeamlessOresConfigData.NETHER_ORE_RARITY,
                SeamlessOresConfigData.NETHER_ORE_RARITY_MIN, SeamlessOresConfigData.NETHER_ORE_RARITY_MAX,
                SeamlessOresConfigData.NETHER_ORE_RARITY_DEFAULT));
        options.add(new IntOption("nether", "netherVeinSize", SeamlessOresConfigData.NETHER_VEIN_SIZE,
                SeamlessOresConfigData.NETHER_VEIN_SIZE_MIN, SeamlessOresConfigData.NETHER_VEIN_SIZE_MAX,
                SeamlessOresConfigData.NETHER_VEIN_SIZE_DEFAULT));

        options.add(new BoolOption("create", "createZinc", SeamlessOresConfigData.CREATE_ZINC, true));
        options.add(new IntOption("create", "zincVeinSize", SeamlessOresConfigData.ZINC_VEIN_SIZE,
                SeamlessOresConfigData.ZINC_VEIN_SIZE_MIN, SeamlessOresConfigData.ZINC_VEIN_SIZE_MAX,
                SeamlessOresConfigData.ZINC_VEIN_SIZE_DEFAULT));

        options.add(new BoolOption("mythic_upgrades", "mythicUpgrades",
                SeamlessOresConfigData.MYTHIC_UPGRADES, true));
        options.add(new BoolOption("mythic_upgrades", "netherGems",
                SeamlessOresConfigData.NETHER_GEMS, true));
        options.add(new IntOption("mythic_upgrades", "netherGemSize",
                SeamlessOresConfigData.NETHER_GEM_SIZE, SeamlessOresConfigData.NETHER_GEM_SIZE_MIN,
                SeamlessOresConfigData.NETHER_GEM_SIZE_MAX, SeamlessOresConfigData.NETHER_GEM_SIZE_DEFAULT));
    }

    @Override
    protected void init() {
        int x = this.width / 2 - ROW_WIDTH / 2;

        int tabWidth = (ROW_WIDTH - GAP * (CATEGORIES.length - 1)) / CATEGORIES.length;
        for (int i = 0; i < CATEGORIES.length; i++) {
            final int index = i;
            Button tab = Button.builder(
                            Component.translatable("text.autoconfig." + Constants.MOD_ID
                                    + ".category." + CATEGORIES[i]),
                            button -> selectCategory(index))
                    .bounds(x + i * (tabWidth + GAP), 28, tabWidth, TAB_HEIGHT)
                    .build();
            // The tab you are on is not clickable, which is also what marks it as selected.
            tab.active = i != category;
            addRenderableWidget(tab);
        }

        int y = HEADER_BOTTOM;
        for (Option option : options) {
            if (!option.category.equals(CATEGORIES[category])) {
                continue;
            }
            AbstractWidget widget = option.createWidget(x, y);
            widget.setTooltip(option.tooltip());
            addRenderableWidget(widget);
            addRenderableWidget(Button.builder(
                            Component.translatable("gui." + Constants.MOD_ID + ".reset"),
                            button -> option.resetToDefault())
                    .bounds(x + OPTION_WIDTH + GAP, y, RESET_WIDTH, WIDGET_HEIGHT)
                    .build());
            y += ROW_HEIGHT;
        }

        // Pinned to the bottom of the screen rather than under the last row, so the buttons do not
        // move as you switch between pages of different lengths.
        int footerY = this.height - WIDGET_HEIGHT - 12;
        int buttonWidth = (ROW_WIDTH - GAP) / 2;
        addRenderableWidget(Button.builder(
                        Component.translatable("gui." + Constants.MOD_ID + ".reset_all"),
                        button -> {
                            options.forEach(Option::resetToDefault);
                            rebuildWidgets();
                        })
                .bounds(x, footerY, buttonWidth, WIDGET_HEIGHT)
                .build());
        addRenderableWidget(Button.builder(CommonComponents.GUI_DONE, button -> onClose())
                .bounds(x + buttonWidth + GAP, footerY, buttonWidth, WIDGET_HEIGHT)
                .build());
    }

    private void selectCategory(int index) {
        this.category = index;
        rebuildWidgets();
    }

    @Override
    public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
        super.render(graphics, mouseX, mouseY, partialTick);
        graphics.drawCenteredString(this.font, this.title, this.width / 2, 12, 0xFFFFFF);
    }

    @Override
    public void onClose() {
        // Write every page back, persist once, then push into the running game. Worldgen reads the
        // holder at server start, so a change made in-world takes effect the next time a world is
        // loaded - the same semantics as the Cloth screen on the other two loaders.
        options.forEach(Option::commit);
        SeamlessOresConfigData.save();
        SeamlessOresConfigData.applyToRuntime();
        if (this.minecraft != null) {
            this.minecraft.setScreen(parent);
        }
    }

    /**
     * One configurable value: which page it belongs to, its pending value, and how to build a
     * widget for it. Pending values outlive the widgets so switching tabs never discards an edit.
     */
    private abstract static class Option {

        final String category;
        final String name;

        Option(String category, String name) {
            this.category = category;
            this.name = name;
        }

        String labelKey() {
            return "text.autoconfig." + Constants.MOD_ID + ".option." + name;
        }

        /**
         * Cloth writes a single-line tooltip as {@code <key>.@Tooltip} and a multi-line one as
         * {@code .@Tooltip[0]}, {@code [1]}, ... There is no count anywhere in the lang file, so
         * probe: take the plain key if it resolves, else read indices until one does not.
         */
        Tooltip tooltip() {
            String single = labelKey() + ".@Tooltip";
            if (net.minecraft.client.resources.language.I18n.exists(single)) {
                return Tooltip.create(Component.translatable(single));
            }
            Component text = null;
            for (int i = 0; net.minecraft.client.resources.language.I18n.exists(single + "[" + i + "]"); i++) {
                Component line = Component.translatable(single + "[" + i + "]");
                text = text == null ? line : text.copy().append("\n").append(line);
            }
            return text == null ? null : Tooltip.create(text);
        }

        abstract AbstractWidget createWidget(int x, int y);

        abstract void resetToDefault();

        abstract void commit();
    }

    /** On/off option, shown as a button that flips its own label. */
    private static final class BoolOption extends Option {

        private final ForgeConfigSpec.BooleanValue config;
        private final boolean defaultValue;
        private boolean value;

        BoolOption(String category, String name, ForgeConfigSpec.BooleanValue config, boolean defaultValue) {
            super(category, name);
            this.config = config;
            this.defaultValue = defaultValue;
            this.value = config.get();
        }

        @Override
        AbstractWidget createWidget(int x, int y) {
            return Button.builder(message(), button -> {
                        value = !value;
                        button.setMessage(message());
                    })
                    .bounds(x, y, OPTION_WIDTH, WIDGET_HEIGHT)
                    .build();
        }

        private Component message() {
            return Component.translatable(labelKey())
                    .append(": ")
                    .append(value ? CommonComponents.OPTION_ON : CommonComponents.OPTION_OFF);
        }

        @Override
        void resetToDefault() {
            value = defaultValue;
        }

        @Override
        void commit() {
            config.set(value);
        }
    }

    /** Bounded integer option, shown as a slider labelled "Label: value". */
    private static final class IntOption extends Option {

        private final ForgeConfigSpec.IntValue config;
        private final int min;
        private final int max;
        private final int defaultValue;
        private int value;

        IntOption(String category, String name, ForgeConfigSpec.IntValue config,
                  int min, int max, int defaultValue) {
            super(category, name);
            this.config = config;
            this.min = min;
            this.max = max;
            this.defaultValue = defaultValue;
            this.value = config.get();
        }

        @Override
        AbstractWidget createWidget(int x, int y) {
            return new IntSlider(x, y, this);
        }

        @Override
        void resetToDefault() {
            value = defaultValue;
        }

        @Override
        void commit() {
            config.set(value);
        }
    }

    /** Slider bound to an {@link IntOption}; the option owns the value, the slider only edits it. */
    private static final class IntSlider extends AbstractSliderButton {

        private final IntOption option;

        IntSlider(int x, int y, IntOption option) {
            super(x, y, OPTION_WIDTH, WIDGET_HEIGHT, Component.empty(),
                    (double) (option.value - option.min) / (option.max - option.min));
            this.option = option;
            updateMessage();
        }

        @Override
        protected void updateMessage() {
            setMessage(Component.translatable(option.labelKey())
                    .append(": ")
                    .append(Component.literal(Integer.toString(option.value))));
        }

        @Override
        protected void applyValue() {
            option.value = option.min + (int) Math.round(this.value * (option.max - option.min));
        }
    }
}
